<link rel="stylesheet" href="%pluginUrl%/DateTimestamp/css/style.css" type="text/css" media="all"/>
<link rel="stylesheet" href="%pluginUrl%/DateTimestamp/css/ui-lightness/jquery-ui-1.8.14.custom.css" type="text/css" media="all"/>

<script type="text/javascript" src="%pluginUrl%/DateTimestamp/js/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="%pluginUrl%/DateTimestamp/js/jquery-ui-1.8.14.min.js"></script>
<script type="text/javascript" src="%pluginUrl%/DateTimestamp/js/jquery-timepicker0.9.6.js"></script>
<script type="text/javascript" src="%pluginUrl%/DateTimestamp/js/validate.js"></script>
<script type="text/javascript" src="%pluginUrl%/DateTimestamp/js/validate_form.js"></script>
